# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'videoWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_videoWindow(object):
    def setupUi(self, videoWindow):
        videoWindow.setObjectName("videoWindow")
        videoWindow.resize(628, 396)
        self.centralwidget = QtWidgets.QWidget(videoWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        videoWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(videoWindow)
        QtCore.QMetaObject.connectSlotsByName(videoWindow)

    def retranslateUi(self, videoWindow):
        _translate = QtCore.QCoreApplication.translate
        videoWindow.setWindowTitle(_translate("videoWindow", "videoWindow"))
